version: 2

multi-ecosystem-groups:
  dependencies:
    schedule:
      interval: weekly

updates:
  - package-ecosystem: npm
    directory: /
    patterns:
      - "*"
    multi-ecosystem-group: dependencies
    open-pull-requests-limit: 1

  - package-ecosystem: github-actions
    directory: /
    patterns:
      - "*"
    multi-ecosystem-group: dependencies
    open-pull-requests-limit: 1
